
import { ThemeProvider } from '@/context/ThemeContext';
import type { Metadata } from "next";
import ReduxProvider from './ReduxProvider';

import "./globals.css";


import { Inter } from 'next/font/google'
import { Roboto_Mono } from 'next/font/google'


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        <ReduxProvider>
          <ThemeProvider>
            
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
